<?php

namespace Foggyline\ShipmentBundle\Repository;

/**
 * DynamicRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynamicRateRepository extends \Doctrine\ORM\EntityRepository
{
}
