<?php

namespace Foggyline\SalesBundle\Repository;

/**
 * SalesOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
