<?php

namespace Foggyline\CatalogBundle\Repository;

/**
 * TeeestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeeestRepository extends \Doctrine\ORM\EntityRepository
{
}
